# data set size
#CFLAGS := -DMINI_DATASET=1
#CFLAGS := -DSMALL_DATASET=1
#CFLAGS := -DSTANDARD_DATASET=1
#CFLAGS := -DLARGE_DATASET=1
CFLAGS := -DEXTRALARGE_DATASET=1

all:
	nvcc -O3 ${CUFILES} -I${PATH_TO_UTILS} -o ${EXECUTABLE} ${CFLAGS}
#	nvcc -O3 ${CUFILES} -I${PATH_TO_UTILS} -o ${EXECUTABLE} 
clean:
	rm -f *~ *.exe
